INSERT INTO `accountcode`(`code`, `department`, `committee`, `type`) 
VALUES
('10101', 'Executive', 'Executive', 'General'),
('10102', 'Executive', 'Executive', 'Misc'),
('10103', 'Executive', 'Executive', 'Travel'),
('10104', 'Executive', 'Executive', 'Staff Accomodations'),
('10105', 'Executive', 'Executive', 'Events'),
('10106', 'Executive', 'Executive', 'Retreat'),
('20101', 'Marketing', 'Marketing', 'General'),
('20102', 'Marketing', 'Marketing', 'Misc'),
('20103', 'Marketing', 'Marketing', 'Events'),
('20201', 'Marketing', 'Networking', 'General'),
('20202', 'Marketing', 'Networking', 'Travel'),
('20301', 'Marketing', 'CreativeMedia', 'General'),
('20302', 'Marketing', 'CreativeMedia', 'Welcome Packets'),
('20401', 'Marketing', 'Production', 'General'),
('20402', 'Marketing', 'Production', 'Stage Design'),
('20403', 'Marketing', 'Production', 'Misc'),
('20414', 'Marketing', 'Production', 'Technical Services General'),
('20415', 'Marketing', 'Production', 'Technical Services HIU'),
('30101', 'Program', 'Program', 'General'),
('30102', 'Program', 'Program', 'Honorarium'),
('30113', 'Program', 'Program', 'Community Service General'),
('40101', 'Operations', 'Finance', 'General'),
('40102', 'Operations', 'Finance', 'Misc'),
('40103', 'Operations', 'Finance', 'Banking'),
('40104', 'Operations', 'Finance', 'Registration'),
('40105', 'Operations', 'Finance', 'Insurance'),
('40106', 'Operations', 'Finance', 'Fundraising'),
('40201', 'Operations', 'ConferenceServices', 'General'),
('40202', 'Operations', 'ConferenceServices', 'Misc'),
('40203', 'Operations', 'ConferenceServices', 'Pre-Conference General'),
('40204', 'Operations', 'ConferenceServices', 'Dorm Accomodations'),
('40205', 'Operations', 'ConferenceServices', 'Food'),
('40206', 'Operations', 'ConferenceServices', 'Counselor Services General'),
('40207', 'Operations', 'ConferenceServices', 'Counselor Services Workshops'),
('40301', 'Operations', 'SystemsDevelopment', 'General'),
('40302', 'Operations', 'SystemsDevelopment', 'Misc'),
('40303', 'Operations', 'SystemsDevelopment', 'Web App'),
('40304', 'Operations', 'SystemsDevelopment', 'Website');